lib/arel_extensions/comparators.rb
test/visitors/test_oracle.rb
test/visitors/test_to_sql.rb

It appears that there is quite some redundancy in the tests inside test_to_sql.rb.

Add support for \z in regexps

---

README.md
functions.html
lib/arel_extensions/visitors/sqlite.rb
test/with_ar/all_agnostic_test.rb

The SQLite visitor is bugged under the following conditions:
1. when x = 10, x.floor is expected to be 10 but is 9
2. when x = 10.01, x.floor is expected to be 10 but is 9
3. when x = 0, x.floor is expected to be 0 but is -1
4. when x = -10.99, x.floor is expected to be -11 but is -12
Reimplementing the visitor to use CASE + CAST satisfies these conditions and fixes the floor implementation.

Fix .floor calculations for SQLite

---

lib/arel_extensions/predications.rb
test/visitors/test_to_sql.rb

One would like to be able to run queries such as
```
User.where(User[:id].in [1..10, 20, 30..40, 50, nil])
```
and leave the desugaring to ArelX.
I'm sorry, this is only a draft: it is quite a task to be able to run purely syntactic tests of ArelX: I don't plan to install dbms, I just want to run the dummy tests such as test/visitors/test_to_sql.rb, but I saw no easy means to do it.  In fact I can't even run the code, there might be stupid syntactic errors. sorry about that.
This feature (on dates) would have been valuable in the project I work on.  I was lucky enough that ActiveRecord does support it.

in: accept arrays that contain ranges

---

lib/arel_extensions/visitors/mysql.rb
test/helper.rb
test/test_comparators.rb
test/visitors/test_bulk_insert_oracle.rb
test/visitors/test_bulk_insert_sqlite.rb
test/visitors/test_bulk_insert_to_sql.rb
test/visitors/test_oracle.rb
test/visitors/test_to_sql.rb
test/with_ar/test_bulk_sqlite.rb

Avoid these warnings:
```
DEPRECATED: global use of must_equal from /Users/akim/src/faveod/arel-extensions/test/helper.rb:16. Use _(obj).must_equal instead. This will fail in Minitest 6.
```
I'm not sure I caught all the places that needed to be updated, but there should be less warnings.
I'd like to see the result of the CI.  And then will provide more commits.

tests: comply with recent versions of minitest

---

lib/arel_extensions/boolean_functions.rb

This unbreaks equality checking, and possibly other things that assumed left or right contained anything.
Should fix #30

Override all methods of Arel::Nodes::Or

---

lib/arel_extensions/common_sql_functions.rb
lib/arel_extensions/nodes/date_diff.rb
lib/arel_extensions/nodes/function.rb
lib/arel_extensions/predications.rb
test/real_db_test.rb

This is a revival of https://github.com/Faveod/arel-extensions/pull/27.
Currently if we try to pass the result of `val.mb_chars` to concat, it ends with
ActiveSupport::Multibyte::Chars can not be converted to CONCAT arg
.../gems/2.5.0/gems/arel_extensions-1.2.12/lib/arel_extensions/nodes/function.rb:77:in `convert_to_node'

concat: accept ActiveSupport::Multibyte::Chars

---

lib/arel_extensions/nodes/format.rb
test/with_ar/all_agnostic_test.rb

This gives us more portability of the possible ISO specifiers.  Based on "man strftime".
I could not run the test suite locally, let's wait for the result!

format: transform `%R` into `%H:%M`

---

lib/arel_extensions/visitors/postgresql.rb
test/with_ar/all_agnostic_test.rb

* lib/arel_extensions/visitors/postgresql.rb: Formatting changes.
(Arel::Visitors::PostgreSQL::DATE_FORMAT_DIRECTIVES): Add %%.
(visit_ArelExtensions_Nodes_Format): Don't use gsub in some random
order: scan the string from left to right.
* test/with_ar/all_agnostic_test.rb: Run this test.

pg: `format('%%'` should give` %`, not `%%`

---

lib/arel_extensions/visitors.rb
lib/arel_extensions/visitors/convert_format.rb
lib/arel_extensions/visitors/mssql.rb
lib/arel_extensions/visitors/mysql.rb
lib/arel_extensions/visitors/oracle.rb
lib/arel_extensions/visitors/oracle12.rb
lib/arel_extensions/visitors/postgresql.rb
lib/arel_extensions/visitors/sqlite.rb

I believe there are several issues to fix in the handling of strftime/format.  There's also a number of things I don't understand well.  For instance mssql is not dealt with the same way as the other RDBMS:
```ruby
module ArelExtensions
module Visitors
module MSSQL
```
instead of
```ruby
module ArelExtensions
module Visitors
class Arel::Visitors::PostgreSQL
```
Why this difference?  I believe it's a mistake, introduced in cf49f1124dc76662fd7d0d143a0a7f997f9c41d9.
Anyway, I don't understand the meaning of
```ruby
module ArelExtensions
module Visitors
class Arel::Visitors::PostgreSQL
```
Is there a difference with just
```ruby
class Arel::Visitors::PostgreSQL
```
?
The test suite is running here: https://travis-ci.org/github/Faveod/arel-extensions/builds/743934528

Improvements for strftime

---

lib/arel_extensions/visitors/to_sql.rb

I have failed to reenable the JSON test.  The very first test fails as soon as you activate it.
However, these fixes have been used with success to fix genuine problems.  We should merge and release.
```
commit e95fcaf02a59d1251239b1410bafad1e60ff0cc4
Author: Akim Demaille <akim.demaille@gmail.com>
Date:   Wed Jan 19 15:58:04 2022 +0100
test: unskip json tests
diff --git a/test/with_ar/all_agnostic_test.rb b/test/with_ar/all_agnostic_test.rb
index 4a62486..ec9e039 100644
--- a/test/with_ar/all_agnostic_test.rb
+++ b/test/with_ar/all_agnostic_test.rb
@@ -777,7 +777,6 @@ module ArelExtensions
end
def test_json
-        skip "Can't be tested on travis"
assert_equal 'Arthur', t(@arthur,Arel.json(@name))
assert_equal ["Arthur","Arthur"], parse_json(t(@arthur,Arel.json(@name,@name)))
```

Json fixes

---

test/with_ar/all_agnostic_test.rb
test/with_ar/insert_agnostic_test.rb
test/with_ar/test_bulk_sqlite.rb
test/with_ar/test_math_sqlite.rb
test/with_ar/test_string_mysql.rb
test/with_ar/test_string_sqlite.rb

There's really no good reason for `WthAr`, which really looks like a copy-pasted typo.

style: s/WthAr/WithAr/

---

.github/workflows/ruby.yml
README.md
gemfiles/rails5_2.gemfile
gemfiles/rails6.gemfile
gemfiles/rails6_1.gemfile

This PR does the following:
1. Fix development/test dependencies for rails 6.1, 6.0, and 5.2
1. Add documentation to `README` on how to run tests locally 
1. Separate jobs into `build` and `test`
1. Add `mssql` test for linux: tested against a MS SQL Server 2019 instance
1. Add Windows support (And maybe drop AppVayor in a later instance)? Test `mssql` and the platform-agnostic `to_sql` only.

CI: Github Action re-write + windows support

---

.github/workflows/ruby.yml
gemfiles/rails7.gemfile
lib/arel_extensions/visitors/postgresql.rb
test/real_db_test.rb
test/with_ar/all_agnostic_test.rb
test/with_ar/insert_agnostic_test.rb
test/with_ar/test_bulk_sqlite.rb
test/with_ar/test_math_sqlite.rb
test/with_ar/test_string_mysql.rb
test/with_ar/test_string_sqlite.rb

Hi!
I found a bug when I upgraded to Rails 7. I found it pretty hard to try and work out what was going on so I just fixed it.
I also had to add support files for testing Rails 7. Sorry for the multi-concerned PR but it didn't really make sense including the fix without the support files needed to verify the bug.
You can cherry pick either commit if it's an issue.
I'm not sure my fix is the best fix. Another option I thought of was stripping quotes inside the `Arel::Nodes::As` class so the current visitor could continue to always quote the column. However, I couldn't work out how to do it easily.
Someone else encountered this issue: https://github.com/rails/rails/issues/44099
Rails introduced the problem in https://github.com/rails/rails/commit/7e6e9091e55c3357b0162d44b6ab955ed0c718d5 by …

Rails 7 testing and fixes a double quotation bug

---

.github/workflows/ruby.yml
gemfiles/rails7.gemfile
lib/arel_extensions/helpers.rb
lib/arel_extensions/math.rb
lib/arel_extensions/nodes/case.rb
lib/arel_extensions/nodes/date_diff.rb
lib/arel_extensions/nodes/function.rb
lib/arel_extensions/visitors/mssql.rb
lib/arel_extensions/visitors/oracle.rb
lib/arel_extensions/visitors/postgresql.rb
lib/arel_extensions/visitors/sqlite.rb
test/arelx_test_helper.rb
test/support/fake_record.rb
test/with_ar/all_agnostic_test.rb

Contains fixes to the MS SQL Server test suite.
In addition to the making all the tests pass, this series of patches:
1. Contain patches for other platforms (e.g. `sqlite`), and
2. Introduces flakiness for the `to_sql` tests.
Point (1.) is a side effect of rails 7 libraries. Point (2.) is the result of making the test work: the helper introduced in commit cc6fedff, and called in 5d5ea3d, 24020f51, e7240642, etc. replaces the way introspection to get columns and their types used to be done.
Indeed, we now rely on the `schema_cache` stored in the DB connection itself to get column-level, db, information.
A possible fix for `to_sql` is creating a (or using a pre-existing) Mock ActiveRecord Adapter, and replace the current method used in the test.

SQL Server fixes

---

lib/arel_extensions/helpers.rb
test/visitors/test_to_sql.rb

This PR addresses to_sql test flakiness. The fix is unconvincing, but it works. Further investigation is required if we want a solid test suite.

test: to_sql: fix flakiness

---

test/arelx_test_helper.rb

This initialization was at the source of flakiness in jruby 9.2 .
There's no need for intializing with FakeRecord when every single
test decides whether to use it to do in vitro tests, or connect
directly through proper DB adapters in an integration test.

tests: jruby: remove unnecessary Arel::Table.engine intialization

---

lib/arel_extensions.rb
lib/arel_extensions/helpers.rb
lib/arel_extensions/math.rb
lib/arel_extensions/nodes/case.rb
lib/arel_extensions/nodes/function.rb
lib/arel_extensions/visitors/oracle.rb
lib/arel_extensions/visitors/sqlite.rb
test/with_ar/all_agnostic_test.rb

Never throw exceptions, always return `nil` instead. This is useful for subqueries.

Fix column_of behavior for missing columns

---

.github/workflows/ruby.yml
gemspecs/arel_extensions-v1.gemspec
gemspecs/arel_extensions-v2.gemspec
lib/arel_extensions.rb
lib/arel_extensions/visitors/mssql.rb
lib/arel_extensions/visitors/mysql.rb
lib/arel_extensions/visitors/oracle.rb
test/with_ar/all_agnostic_test.rb

Arel already defines Rollup for Postgres.
This patch adds support for MySQL/MSSQL/ORACLE.

Feature: Add RollUp

---

NEWS.md

I think we should really maintain this.  As a user of packages, NEWS/ChangeLog is something I often read.

Add a NEWS file

---

NEWS.md
lib/arel_extensions/date_duration.rb
lib/arel_extensions/nodes/formatted_date.rb
lib/arel_extensions/visitors/mssql.rb
lib/arel_extensions/visitors/mysql.rb
lib/arel_extensions/visitors/oracle.rb
lib/arel_extensions/visitors/postgresql.rb
lib/arel_extensions/visitors/to_sql.rb
test/with_ar/all_agnostic_test.rb

This PR does 2 things:
1. Fixes a bug in `Format` for mysql, where type inference can go wrong if `return_type` doesn't exist.
2. Introduce `format_date`, mirroring `format_number`

Better `format` + `formatted_date`

---

lib/arel_extensions/visitors/to_sql.rb
test/arelx_test_helper.rb
test/with_ar/all_agnostic_test.rb

https://datatracker.ietf.org/doc/html/rfc8259:
> All Unicode characters may be placed within the quotation marks,  except for the characters that MUST be escaped: quotation mark,  reverse solidus, and the control characters (U+0000 through U+001F).
We should also escape the remaining ones, using \u.
Where are the tests for this?

json: escape all the "popular" control characters

---

.github/workflows/ruby.yml
NEWS.md
README.md
lib/arel_extensions.rb
lib/arel_extensions/visitors/postgresql.rb
test/with_ar/all_agnostic_test.rb

In this PR 2 things happened for postgres:
1. Casting to timestamps is done through `timestamp without timezone`.
2. Converting timezones, when we only specify a string (the destination), considers that we're starting from UTC, and doesn't leave it to interpretation. If you want to specify the starting timezone, pass a hash.

potsgres: default to UTC when formatting dates.

---

lib/arel_extensions/visitors/mssql.rb
test/real_db_test.rb

Formatted date/datetime cannot be used in date operation in SqlServer.
This PR fixes it

Mssql date time literal support

---

.github/workflows/ruby.yml
NEWS.md
lib/arel_extensions/visitors.rb

Also contains an improvement on CI build: no more duplicates on PRs.

Turn on SQL Server warnings only when necessary

---

NEWS.md
lib/arel_extensions/visitors/mssql.rb

This might be the cause of some issues with SQL Server with Rails > 4, inventing columns called TRUE.

mssql: restrict date quoting to arel <= 6

---

NEWS.md
gemfiles/rails6_1.gemfile
gemfiles/rails7.gemfile
gemfiles/rails7_1.gemfile
gemfiles/rails7_2.gemfile
lib/arel_extensions.rb
lib/arel_extensions/attributes.rb
lib/arel_extensions/nodes/aggregate_function.rb
lib/arel_extensions/nodes/function.rb
lib/arel_extensions/nodes/rollup.rb
lib/arel_extensions/string_functions.rb
lib/arel_extensions/version.rb
lib/arel_extensions/visitors/mssql.rb
lib/arel_extensions/visitors/mysql.rb
lib/arel_extensions/visitors/oracle.rb
lib/arel_extensions/visitors/postgresql.rb
lib/arel_extensions/visitors/to_sql.rb
lib/arel_extensions/warning.rb
test/arelx_test_helper.rb
test/with_ar/all_agnostic_test.rb
version_v1.rb
version_v2.rb

1. get rid of a lot of useless warnings polluting the test suite
2. fix a bug from group_concat.

Use warning module for deprecation warnings

---

NEWS.md
lib/arel_extensions/warning.rb

Using ruby's Warning module was a wrong. ActiveRecords depends on ActiveSupport, and this is more proper especially for rails applications.

Use ActiveSupport::Deprecation instead of Ruby's Warning

---

NEWS.md
lib/arel_extensions/string_functions.rb

To reproduce it, open rails console, make a `t = Table::new("tab")`, then try to t[:col]. StringFunctions' [] will be called with the wrong types. No backtrace, no nothing.
If you want a backtrace, you can do `pp t[:col]`. It turns out that our [] was shadowing Struct's own [] that is defined in C, not in Ruby, and it explaians why it was impossible to get the `source_location` from the call stack.

string-functions: fix a subtle bug on `[]` calls of `Table`
